### ISSUE TITLE
Error: "['abstract'] not in index"

### ISSUE THREAD

**Issue by YuNangoChen** [FedeClaudi/refy#5]
Hi Federico,

I am new to this package. I set up my code according to your helpful instruction but had this error now. May I know if you have any idea for this?

**Comment by YuNangoChen** [comment]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                                                                  │
│ c:\Users\86155\Downloads\reference\refyuse.py:8 in <module>                                      │
│                                                                                                  │
│   5   n_days=30,               # fetch preprints from the last N days                            │
│   6   html_path="C:\\Users\\86155\\Downloads\\reference\\test.html",   # save results to a .     │
│   7   N=10,                     # number of recomended papers                                    │
│ ❱ 8   show_html=True,                                                                            │
│   9 )                                                                                            │
│ C:\ProgramData\Anaconda3\envs\untitled2\lib\site-packages\refy\recomend.py:58 in __init__        │
│                                                                                                  │
│    55 │   │                                                                                      │
│    56 │   │   # load user data                                                                   │
│    57 │   │   logger.debug("Loading user papers")                                                │
│ ❱  58 │   │   self.user_papers = load_user_input(user_data_filepath)                             │
│    59 │   │   self.user_abstracts = {                                                            │
│    60 │   │   │   p["id"]: p.abstract for i, p in self.user_papers.iterrows()                    │
│    61 │   │   }                                                                                  │
│                                                                                                  │
│ C:\ProgramData\Anaconda3\envs\untitled2\lib\site-packages\refy\input.py:41 in load_user_input    │
│                                                                                                  │
│   38 │                                                                                           │
│   39 │   # Clean up data                                                                         │
│   40 │   data = pd.DataFrame(data.values())                                                      │
│ ❱ 41 │   data = data[["title", "journal", "author", "abstract"]]                                 │
│   42 │   data.columns = ["title", "journal", "authors", "abstract"]                              │
│   43 │   data["id"] = data["title"]                                                              │
│   44                                                                                             │
│                                                                                                  │
│ C:\ProgramData\Anaconda3\envs\untitled2\lib\site-packages\pandas\core\frame.py:3030 in           │
│ __getitem__                                                                                      │
│                                                                                                  │
│   3027 │   │   else:                                                                             │
│   3028 │   │   │   if is_iterator(key):                                                          │
│   3029 │   │   │   │   key = list(key)                                                           │
│ ❱ 3030 │   │   │   indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]  │
│   3031 │   │                                                                                     │
│   3032 │   │   # take() does not accept boolean indexers                                         │
│   3033 │   │   if getattr(indexer, "dtype", None) == bool:                                       │
│                                                                                                  │
│ C:\ProgramData\Anaconda3\envs\untitled2\lib\site-packages\pandas\core\indexing.py:1266 in        │
│ _get_listlike_indexer                                                                            │
│                                                                                                  │
│   1263 │   │   else:                                                                             │
│   1264 │   │   │   keyarr, indexer, new_indexer = ax._reindex_non_unique(keyarr)                 │
│   1265 │   │                                                                                     │
│ ❱ 1266 │   │   self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)   │
│   1267 │   │   return keyarr, indexer                                                            │
│   1268 │                                                                                         │
│   1269 │   def _validate_read_indexer(                                                           │
│                                                                                                  │
│ C:\ProgramData\Anaconda3\envs\untitled2\lib\site-packages\pandas\core\indexing.py:1316 in        │
│ _validate_read_indexer                                                                           │
│                                                                                                  │
│   1313 │   │   │   # some cases (e.g. setting) in which "raise_missing" will be False            │
│   1314 │   │   │   if raise_missing:                                                             │
│   1315 │   │   │   │   not_found = list(set(key) - set(ax))                                      │
│ ❱ 1316 │   │   │   │   raise KeyError(f"{not_found} not in index")                               │
│   1317 │   │   │                                                                                 │
│   1318 │   │   │   not_found = key[missing_mask]                                                 │
│   1319                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: "['abstract'] not in index"

**Comment by FedeClaudi** [comment]
Hey,

It's not easy to know without more details, but I think it might have to do with an entry in your `.bib` text not having a `abstract` key. Can you double check that>

**Comment by YuNangoChen** [comment]
Hi, thanks very much for the reply. I tried adding abstracts in, and now refy is working on my computer. That's really cool! Since I found the BibTeX which google scholar provides are mostly with all the information except abstracts, is there any option for generating a .bib library with abstract, or do I have to always add the abstract for an article by hand?

**Comment by FedeClaudi** [comment]
Excellent, hope you enjoy.

I personally use [paperpile](https://paperpile.com/) to manage my library and it exports `.bib` which includes abstracts. I think other reference managers will do the same, but I'm not sure.
